id: PE903E91E
initial_creation_type: ocr
source_metadata:
  volumes:
    bdbc1287e1d54fdfaef0ed56a507ce52:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རིན་པོ་ཆེ་རྒྱན་གྱི་སྒྲུབ་པ།
      total_pages: 1544
      volume_number: 12
