id: PE903E91E
initial_creation_type: ocr
source_metadata:
  volumes:
    c2b36d4d57a64bb4a2aea0901b72c28c:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: རིན་པོ་ཆེ་རྒྱན་གྱི་སྒྲུབ་པ།
      total_pages: 1544
      volume_number: 12
